name: "PR Checks for `main` documentation"
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths: # Only run checks on changes to documentation
      - "**/docs/*"
      - "*/README.md"

jobs:
  build:
    name: "Generate Latest Documentation"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@b70bbae19637171d6cf9311f06a59f1c15e2598b

      - name: "Generate Documentation"
        run: ./gradlew dokkaHtmlMultiModule -Pgithub.user=${{ secrets.BUILD_USER }} -Pgithub.token=${{ secrets.BUILD_TOKEN }}

      - name: Upload Dokka Docs
        uses: actions/upload-artifact@v4
        with:
          path: "build/dokka/htmlMultiModule/"
          name: commonsense-dokka-docs
