name: "PR Checks for `main`"
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build-app-android:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@b70bbae19637171d6cf9311f06a59f1c15e2598b
      - name: Run Debug Unit Tests
        run: ./gradlew testDebugUnitTest -Pgithub.user=${{ secrets.BUILD_USER }} -Pgithub.token=${{ secrets.BUILD_TOKEN }}
      - name: Upload Debug Unit Test Coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          path: "build/reports/kover/html/*"
          name: android-debug-test-coverage
      - name: Upload Debug Unit Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: "**/build/reports/tests/testDebugUnitTest/*"
          name: android-debug-test-reports

  build-app-desktop:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@b70bbae19637171d6cf9311f06a59f1c15e2598b
      - name: Build Desktop App
        run: ./gradlew jvmTest -Pgithub.user=${{ secrets.BUILD_USER }} -Pgithub.token=${{ secrets.BUILD_TOKEN }}
      - name: Upload Jvm Test Coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          path: "build/reports/kover/html/*"
          name: jvm-test-coverage
      - name: Upload Jvm Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: "**/build/reports/tests/jvmTest/*"
          name: jvm-test-reports
