name: "Release for `main`"
on:
  push:
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build-app-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@b70bbae19637171d6cf9311f06a59f1c15e2598b
      - name: Build Android App
        run: ./gradlew :app-android:bundleRelease -Pgithub.user=${{ secrets.BUILD_USER }} -Pgithub.token=${{ secrets.BUILD_TOKEN }}
      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          path: app-android/build/outputs/bundle/release/app-android-release.aab
          name: app-android-release.aab

  build-app-desktop:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle@b70bbae19637171d6cf9311f06a59f1c15e2598b
      - name: Build Desktop App
        run: ./gradlew :app-desktop:createDistributable -Pgithub.user=${{ secrets.BUILD_USER }} -Pgithub.token=${{ secrets.BUILD_TOKEN }}
      - name: Upload Desktop App
        uses: actions/upload-artifact@v4
        with:
          path: app-desktop/build/libs/app-desktop.jar
          name: app-desktop.jar
